

export enum FieldType {
  STRING = 'string',
  NUMBER = 'number',
  BOOLEAN = 'boolean',
  OBJECT = 'object',
  ARRAY = 'array',
  NULL = 'null'
}

export enum GenerationStrategy {
  INCREMENT = 'increment', // 自增
  RANDOM_INT = 'random_int', // 随机整数
  RANDOM_FLOAT = 'random_float', // 随机浮点
  ENUM = 'enum', // 枚举
  UUID = 'uuid', // UUID
  NAME = 'name', // 人名
  EMAIL = 'email', // 邮箱
  DATE = 'date', // 日期
  ADDRESS = 'address', // 地址
  PHONE = 'phone', // 电话
  SENTENCE = 'sentence', // 随机句子
  STATIC = 'static', // 固定值
  REGEX = 'regex', // 正则表达式
  AI_CONTEXT = 'ai_context' // 根据上下文智能生成
}

export interface FieldConfig {
  key: string;
  type: FieldType;
  strategy: GenerationStrategy;
  description?: string; // AI对该字段含义的理解
  sampleValue?: any; // Original value from the sample JSON
  options?: {
    min?: number;
    max?: number;
    step?: number;
    start?: number; // Initial value for increment
    values?: string[]; // Enum values
    format?: string; // Date format
    pattern?: string; // Regex pattern
    staticValue?: any; // Changed from string to any to support strict types
    precision?: number; // Float precision
    groupingConfig?: {
      strategy: 'fixed' | 'even'; // Distribution strategy
      countPerGroup?: number; // Used for 'fixed'
      resetFields?: string[]; // Fields to reset when this group changes
    };
  };
  nested?: FieldConfig[]; // For objects
}

export interface AnalysisResult {
  fields: FieldConfig[];
  originalSampleCount: number;
}

export interface Template {
  id: string;
  name: string;
  createdAt: number;
  config: {
    inputJson: string;
    fields: FieldConfig[];
    customInstructions: string;
    generateCount: number;
    generatedCode?: string; // The JS code generated by AI
  }
}